default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wd_db
test:
  <<: *default
  database: test_wd_db

production:
  <<: *default
  database: prod_wd_db
